dependencies:
  - astropy
  - boost
  - boto
  - cython
  - dask
  - datashader
  - flake8
  - jupyter
  - jupyterlab
  - graphviz
  - holoviews
  - iminuit
  - matplotlib
  - nb_conda
  - numba>=0.44
  - numpy
  - pandas
  - pandoc
  - pip
  - python=3.6
  - scikit-learn
  - scipy
  - sphinx
  - tensorflow
  - tqdm
  - pip:
    - boltons
    - hypothesis
    - nbsphinx
